import { MODS } from "./mods.js";

export const FAQ_CATEGORIES = Object.freeze(["All","General","Installation","Compatibility","Troubleshooting","Development","Releases"]);

export const FAQS = Object.freeze([
 {id:"what-is-torqz-garage",category:"General",question:"What is Torqz Garage?",answer:"Torqz Garage is Project 01, a BeamNG.drive mod in development focused on persistent vehicle ownership and vehicle data."},
 {id:"download-availability",category:"Releases",question:"Can I download Torqz Garage?",answer:"Not yet. Torqz Garage is in development and no public release or download link has been announced."},
 {id:"installation-instructions",category:"Installation",question:"Where are Torqz Garage installation instructions?",answer:"Verified installation steps will be published with a public release. General BeamNG mod-installation information is on the Installation Help page.",href:"install.html"},
 {id:"supported-game-version",category:"Compatibility",question:"Which BeamNG.drive version is supported?",answer:"Compatibility has not been verified or published yet. Torqz Garage is still being tested."},
 {id:"troubleshoot-missing-mod",category:"Troubleshooting",question:"What if a BeamNG mod doesn't appear?",answer:"For a publicly released BeamNG mod, check its download location and the Mod Manager, then review any error messages. These are general troubleshooting steps, not Torqz Garage-specific instructions.",href:"help.html#mod-not-appearing"},
 {id:"troubleshoot-loading",category:"Troubleshooting",question:"Where do I start if a mod won't load?",answer:"Read the game's Mod Manager or console messages and try controlled checks, such as confirming the file is complete and checking for conflicts. Our Troubleshooting Center has general steps.",href:"help.html#mod-not-loading"},
 {id:"progress",category:"Development",question:"What is being developed right now?",answer:"Foundation work is complete and Vehicle Data is the current in-progress milestone. Persistent Garage, UI, and Testing are planned.",href:"mods/project-01.html"},
 {id:"latest-updates",category:"Development",question:"Where can I follow development?",answer:"The Updates page contains verified Torqz Garage development entries, sourced from the project's development log.",href:"updates.html"},
 {id:"known-issues",category:"Troubleshooting",question:"Are there published Torqz Garage issues?",answer:"No Torqz Garage known-issue records have been published yet. That does not mean the development build is bug-free.",href:"known-issues.html"},
 {id:"report-problem",category:"Troubleshooting",question:"Can I report a problem?",answer:"You can prepare a structured bug report to copy. The website does not currently send reports to a server.",href:"report.html#bug"},
 {id:"independent",category:"General",question:"Is Torqz Mods affiliated with BeamNG?",answer:"No. Torqz Mods is an independent modding brand and is not affiliated with BeamNG GmbH."}
]);

export const GUIDES = Object.freeze([
 {id:"mod-not-appearing",title:"Mod not appearing in Mod Manager",category:"Installation",intro:"A publicly released BeamNG mod cannot be found in the in-game Mod Manager.",causes:["The archive was saved outside the game's active mods location.","The download may be incomplete.","The archive structure may not match that mod's instructions."],steps:["Confirm you have a legitimate released mod file. Torqz Garage is not publicly released.","Use BeamNG's launcher to locate the active user folder for your installation.","Check the appropriate mods folder and follow the mod author's install instructions.","Restart BeamNG and check Mod Manager again."],check:"Confirm whether the mod appears and whether Mod Manager shows a warning.",report:"Record the mod name, installation location, game version, and any Mod Manager messages."},
 {id:"mod-not-loading",title:"Installed mod not loading",category:"Loading",intro:"The mod appears installed but its features do not start.",causes:["The mod may not match the current game version.","There may be a conflict or a loading error.","The mod may need instructions or dependencies supplied by its author."],steps:["Read the mod's official instructions and any published compatibility information.","Check the Mod Manager and in-game console for error messages.","For publicly released mods, test with other unrelated mods temporarily disabled if safe to do so.","Restart and reproduce the behavior without changing several settings at once."],check:"Note whether the behavior changes and whether errors remain.",report:"Include the exact console/log messages and the smallest set of steps that reproduces the issue."},
 {id:"conflicting-mods",title:"Suspected mod conflicts",category:"Conflicts",intro:"Two or more installed mods may be interfering with each other.",causes:["Mods may replace or modify overlapping systems.","A mod may have been designed for a different game version."],steps:["Make a note of your current enabled-mod list.","Disable unrelated mods for a controlled comparison; do not delete files you want to keep.","Re-enable mods in small groups to narrow down the conflict.","Check each mod's current support and known compatibility notes."],check:"Identify whether a specific enabled combination reproduces the issue.",report:"List the conflicting mod names and the exact game version."},
 {id:"cache-problems",title:"Possible BeamNG cache problems",category:"Performance",intro:"Outdated cached data may contribute to unexpected behavior in some situations.",causes:["Cached game data may not match changed mod assets or recent game updates."],steps:["Close the game and back up anything important first.","Open BeamNG's launcher Support Tools and use its Clear Cache option, if available for your version.","Follow the launcher prompts and let the game rebuild its cache.","Test again before trying unrelated changes."],check:"Compare the same scenario before and after clearing the cache.",report:"Include whether clearing the cache changed anything and any error messages."},
 {id:"missing-files",title:"Missing or damaged mod files",category:"Installation",intro:"A download or local archive may be incomplete or damaged.",causes:["The transfer may have been interrupted.","An extraction or manual file move may have failed."],steps:["Compare the download to the creator's official release instructions and available checksums if provided.","Do not download replacement files from unverified mirrors.","Re-download a verified public release if the archive is incomplete.","Install it using that mod's documented method."],check:"Check whether the archive is intact and the mod appears normally.",report:"Note the file name, source, any archive errors, and the install steps you followed."},
 {id:"game-compatibility",title:"Game version compatibility",category:"Compatibility",intro:"A mod may not work with every BeamNG.drive version.",causes:["Game changes can affect mod scripts or assets.","The project creator may not have tested your version."],steps:["Find your BeamNG.drive version in the game or launcher.","Look for the mod author's verified compatibility notes.","Avoid assuming an unreleased Torqz Garage build supports a particular version.","If no compatibility statement exists, record the version and wait for verified guidance."],check:"Check for a published compatibility statement before troubleshooting further.",report:"Include the full game version and any mod version shown by the author."},
 {id:"find-logs",title:"Finding BeamNG logs",category:"Diagnostics",intro:"Game logs can help explain why an installed mod failed.",causes:["A script error, missing dependency, or loading warning may be recorded in a log."],steps:["Open BeamNG's launcher and find the option to open or manage the current user folder.","Look for the game logs (commonly named beamng.log); exact folder locations can vary by BeamNG version.","Reproduce the problem, then save the relevant error lines.","Remove personal paths or other sensitive details before sharing a log."],check:"Check that the log corresponds to the session when the problem happened.",report:"Copy the relevant error lines into the Bug Report Builder, not necessarily the entire log."},
 {id:"prepare-report",title:"Preparing a useful bug report",category:"Reporting",intro:"Clear reproduction steps make technical problems easier to investigate.",causes:["Missing context or vague descriptions can make a report hard to reproduce."],steps:["Write a short, specific issue title.","Record the project name and your exact BeamNG version.","List numbered steps that reproduce the issue.","Describe what you expected versus what actually happened.","Include relevant error text with personal information removed."],check:"Make sure someone else could follow your steps without guessing.",report:"Use the Torqz Bug Report Builder to generate and copy the text. Nothing is sent automatically."}
]);

export const KNOWN_ISSUES = Object.freeze(
 MODS.flatMap(project => (project.knownIssues || []).filter(item=>item && item.title && item.status).map(item=>({
  ...item,projectId:project.id,projectName:project.publicName
 })))
);
